version: "3.0"
expectations:
  population_size: 30000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  01_cr_analysis_dataset:
    needs: [generate_cohort]
    run: stata-mp:latest analysis/01_cr_analysis_dataset.do
    outputs:
      moderately_sensitive:
        log: logs/01_cr_analysis_dataset.log
      highly_sensitive:
        check_data: "tempdata/analysis_dataset.dta"
        check_data2: "tempdata/analysis_dataset_ageband_*.dta"
        data: "tempdata/cr_create_analysis_dataset_STSET_*_ageband_*.dta"
        data_eth: "tempdata/analysis_dataset_with_missing_ethnicity.dta"

  02_an_data_checks:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/02_an_data_checks.do 
    outputs:
      moderately_sensitive:
        log: logs/02_an_data_checks.log
        histogram: "output/01_histogram_*.svg"

  03a_an_descriptive_tables:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/03a_an_descriptive_tables.do 
    outputs:
      moderately_sensitive:
        log: logs/03a_an_descriptive_tables.log

  03b_an_descriptive_table_1:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/03b_an_descriptive_table_1.do 
    outputs:
      moderately_sensitive:
        log: logs/03b_an_descriptive_table_1.log
        data: "output/03b_an_descriptive_table_1_kids_cat4_ageband*.txt"

  04a_an_descriptive_tables:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/04a_an_descriptive_tables.do 
    outputs:
      moderately_sensitive:
        log: logs/04a_an_descriptive_tables.log

  04b_an_descriptive_table_2:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/04b_an_descriptive_table_2.do 
    outputs:
      moderately_sensitive:
        log: logs/04b_an_descriptive_table_2.log
        data: "output/04b_an_descriptive_table_2_ageband*.txt"

  06_univariate_analysis:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/06_univariate_analysis.do 
    outputs:
      moderately_sensitive:
        log: logs/06_univariate_analysis.log
        data: "output/an_univariable_cox_models_*_AGESEX_ageband_*.ster"

  07a_an_multivariable_cox_models_demogADJ:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07a_an_multivariable_cox_models_demogADJ.do 
    outputs:
      moderately_sensitive:
        log: logs/07a_an_multivariable_cox_models.log
        data: "output/an_multivariate_cox_models_*_DEMOGADJ_ageband_*.ster"  

  07b_an_multivariable_cox_models_FULL_covid_death:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL.do covid_death 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covid_death.log
        data: "output/an_multivariate_cox_models_covid_death_*_FULLYADJMODEL_ageband_*.ster"

  07b_an_multivariable_cox_models_FULL_covid_tpp_prob:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL.do covid_tpp_prob 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covid_tpp_prob.log
        data: "output/an_multivariate_cox_models_covid_tpp_prob_*_FULLYADJMODEL_ageband_*.ster"

  07b_an_multivariable_cox_models_FULL_covidadmission:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL.do covidadmission 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covidadmission.log
        data: "output/an_multivariate_cox_models_covidadmission_*_FULLYADJMODEL_ageband_*.ster"

  07b_an_multivariable_cox_models_FULL_covid_death_11thJuneCensor:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL_sense_11thJuneCensor.do covid_death 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covid_death_11thJuneCensor.log
        data: "output/an_multivariate_cox_models_covid_death_*_FULLYADJMODEL_ageband_*_11thJuneCensor.ster"

  07b_an_multivariable_cox_models_FULL_covid_tpp_prob_11thJuneCensor:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL_sense_11thJuneCensor.do covid_tpp_prob 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covid_tpp_prob_11thJuneCensor.log
        data: "output/an_multivariate_cox_models_covid_tpp_prob_*_FULLYADJMODEL_ageband_*_11thJuneCensor.ster"

  07b_an_multivariable_cox_models_FULL_covidadmission_11thJuneCensor:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL_sense_11thJuneCensor.do covidadmission 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covidadmission_11thJuneCensor.log
        data: "output/an_multivariate_cox_models_covidadmission_*_FULLYADJMODEL_ageband_*_11thJuneCensor.ster"

  07b_an_multivariable_cox_models_FULL_covid_death_2ndVaccCensor:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL_sense_2ndVaccCensor.do covid_death 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covid_death_2ndVaccCensor.log
        data: "output/an_multivariate_cox_models_covid_death_*_FULLYADJMODEL_ageband_*_2ndVaccCensor.ster"

  07b_an_multivariable_cox_models_FULL_covid_tpp_prob_2ndVaccCensor:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL_sense_2ndVaccCensor.do covid_tpp_prob 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covid_tpp_prob_2ndVaccCensor.log
        data: "output/an_multivariate_cox_models_covid_tpp_prob_*_FULLYADJMODEL_ageband_*_2ndVaccCensor.ster"

  07b_an_multivariable_cox_models_FULL_covidadmission_2ndVaccCensor:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/07b_an_multivariable_cox_models_FULL_sense_2ndVaccCensor.do covidadmission 
    outputs:
      moderately_sensitive:
        log: logs/07b_an_multivariable_cox_models_covidadmission_2ndVaccCensor.log
        data: "output/an_multivariate_cox_models_covidadmission_*_FULLYADJMODEL_ageband_*_2ndVaccCensor.ster"

  08_an_tablecontent_HRtable_covid_tpp_prob:
    needs:
      - 01_cr_analysis_dataset
      - 06_univariate_analysis
      - 07a_an_multivariable_cox_models_demogADJ
      - 07b_an_multivariable_cox_models_FULL_covid_tpp_prob
    run: stata-mp:latest analysis/08_an_tablecontent_HRtable.do covid_tpp_prob
    outputs:
      moderately_sensitive:
        log: logs/08_an_tablecontent_HRtable_covid_tpp_prob.log
        data: "output/an_tablecontents_HRtable_covid_tpp_prob.txt"

  08_an_tablecontent_HRtable_covid_death:
    needs:
      - 01_cr_analysis_dataset
      - 06_univariate_analysis
      - 07a_an_multivariable_cox_models_demogADJ
      - 07b_an_multivariable_cox_models_FULL_covid_death
    run: stata-mp:latest analysis/08_an_tablecontent_HRtable.do covid_death
    outputs:
      moderately_sensitive:
        log: logs/08_an_tablecontent_HRtable_covid_death.log
        data: "output/an_tablecontents_HRtable_covid_death.txt"

  08_an_tablecontent_HRtable_covidadmission:
    needs:
      - 01_cr_analysis_dataset
      - 06_univariate_analysis
      - 07a_an_multivariable_cox_models_demogADJ
      - 07b_an_multivariable_cox_models_FULL_covidadmission
    run: stata-mp:latest analysis/08_an_tablecontent_HRtable.do covidadmission
    outputs:
      moderately_sensitive:
        log: logs/08_an_tablecontent_HRtable_covidadmission.log
        data: "output/an_tablecontents_HRtable_covidadmission.txt"

  10_an_interaction_cox_models_sex_covid_death:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/10_an_interaction_cox_models_sex.do covid_death 
    outputs:
      moderately_sensitive:
        log: logs/10_an_interaction_cox_models_sex_covid_death.log
        data: "output/an_interaction_cox_models_covid_death_*_male_*.ster"

  10_an_interaction_cox_models_sex_covid_tpp_prob:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/10_an_interaction_cox_models_sex.do covid_tpp_prob 
    outputs:
      moderately_sensitive:
        log: logs/10_an_interaction_cox_models_sex_covid_tpp_prob.log
        data: "output/an_interaction_cox_models_covid_tpp_prob_*_male_*.ster"

  10_an_interaction_cox_models_sex_covidadmission:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/10_an_interaction_cox_models_sex.do covidadmission 
    outputs:
      moderately_sensitive:
        log: logs/10_an_interaction_cox_models_sex_covidadmission.log
        data: "output/an_interaction_cox_models_covidadmission_*_male_*.ster"

  10_an_interaction_cox_models_shield_covid_death:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/10_an_interaction_cox_models_shield.do covid_death 
    outputs:
      moderately_sensitive:
        log: logs/10_an_interaction_cox_models_shield_covid_death.log
        data: "output/an_interaction_cox_models_covid_death_*_shield_*.ster"

  10_an_interaction_cox_models_shield_covid_tpp_prob:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/10_an_interaction_cox_models_shield.do covid_tpp_prob 
    outputs:
      moderately_sensitive:
        log: logs/10_an_interaction_cox_models_shield_covid_tpp_prob.log
        data: "output/an_interaction_cox_models_covid_tpp_prob_*_shield_*.ster"

  10_an_interaction_cox_models_shield_covidadmission:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/10_an_interaction_cox_models_shield.do covidadmission 
    outputs:
      moderately_sensitive:
        log: logs/10_an_interaction_cox_models_shield_covidadmission.log
        data: "output/an_interaction_cox_models_covidadmission_*_shield_*.ster"

  10_an_interaction_cox_models_vaccine_covid_tpp_prob:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/10_an_interaction_cox_models_vaccine.do covid_tpp_prob 
    outputs:
      moderately_sensitive:
        log: logs/10_an_interaction_cox_models_vaccine_covid_tpp_prob.log
        data: "output/an_interaction_cox_models_covid_tpp_prob_*_vaccine_*.ster"

  10a_an_interaction_cox_models_vaccine_sex_shield_covid_tpp_prob:
    needs: [01_cr_analysis_dataset]
    run: stata-mp:latest analysis/10a_an_interaction_cox_models_vaccine_sex_shield.do covid_tpp_prob 
    outputs:
      moderately_sensitive:
        log: logs/10_an_interaction_cox_models_vaccine_covid_tpp_prob_sex_shield.log
        data: "output/an_interaction_cox_models_covid_tpp_prob_*_vaccine_*male*.ster"
        data2: "output/an_interaction_cox_models_covid_tpp_prob_*_vaccine_*shield*.ster"

  11_an_interaction_HR_tables_forest_covid_tpp_prob:
    needs:
      - 10_an_interaction_cox_models_sex_covid_tpp_prob
      - 10_an_interaction_cox_models_shield_covid_tpp_prob
    run: stata-mp:latest analysis/11_an_interaction_HR_tables_forest.do covid_tpp_prob
    outputs:
      moderately_sensitive:
        log: logs/11_an_interaction_HR_tables_forest_covid_tpp_prob.log
        data: "output/11_an_int_tab_contents_HRtable_covid_tpp_prob.txt"

  11_an_interaction_HR_tables_forest_covid_death:
    needs:
      - 10_an_interaction_cox_models_sex_covid_death
      - 10_an_interaction_cox_models_shield_covid_death
    run: stata-mp:latest analysis/11_an_interaction_HR_tables_forest.do covid_death
    outputs:
      moderately_sensitive:
        log: logs/11_an_interaction_HR_tables_forest_covid_death.log
        data: "output/11_an_int_tab_contents_HRtable_covid_death.txt"

  11_an_interaction_HR_tables_forest_covidadmission:
    needs:
      - 10_an_interaction_cox_models_sex_covidadmission
      - 10_an_interaction_cox_models_shield_covidadmission
    run: stata-mp:latest analysis/11_an_interaction_HR_tables_forest.do covidadmission
    outputs:
      moderately_sensitive:
        log: logs/11_an_interaction_HR_tables_forest_covidadmission.log
        data: "output/11_an_int_tab_contents_HRtable_covidadmission.txt"

  15_anHRfigure_all_outcomes_2021:
    needs:  
      - 07b_an_multivariable_cox_models_FULL_covid_tpp_prob
      - 07b_an_multivariable_cox_models_FULL_covidadmission
      - 07b_an_multivariable_cox_models_FULL_covid_death
    run: stata-mp:latest analysis/15_anHRfigure_all_outcomes_2021.do
    outputs:
      moderately_sensitive:
        log: logs/15_an_tablecontents_HRtable_all_outcomes_ANALYSES.log
        data: "output/15_an_tablecontents_HRtable_all_outcomes_ANALYSES.txt"

  11_an_interaction_HR_tables_forest_vaccine_main_analysis_covid_tpp_prob:
    needs:
      - 10_an_interaction_cox_models_vaccine_covid_tpp_prob
      - 01_cr_analysis_dataset
    run: stata-mp:latest analysis/11_an_interaction_HR_tables_forest_vaccine_main_analysis.do covid_tpp_prob
    outputs:
      moderately_sensitive:
        log: logs/11_an_interaction_HR_tables_forest_covid_tpp_prob_vaccine_main.log
        data: "output/11_an_int_tab_contents_HRtable_covid_tpp_prob_vaccine_main.txt"

  11_an_interaction_HR_tables_forest_vaccine_strat_analysis_covid_tpp_prob:
    needs:
      - 10a_an_interaction_cox_models_vaccine_sex_shield_covid_tpp_prob
      - 01_cr_analysis_dataset
    run: stata-mp:latest analysis/11_an_interaction_HR_tables_forest_vaccine_strat_analysis.do covid_tpp_prob
    outputs:
      moderately_sensitive:
        log: logs/11_an_interaction_HR_tables_forest_vaccine_strat_covid_tpp_prob.log
        data: "output/11_an_int_tab_contents_HRtable_covid_tpp_prob_vaccine_strat.txt"

  15_anHRfigure_data_all_outcomes_2021_SENSE:
    needs:  
      - 07b_an_multivariable_cox_models_FULL_covid_tpp_prob_11thJuneCensor
      - 07b_an_multivariable_cox_models_FULL_covidadmission_11thJuneCensor
      - 07b_an_multivariable_cox_models_FULL_covid_death_11thJuneCensor
      - 07b_an_multivariable_cox_models_FULL_covid_tpp_prob_2ndVaccCensor
      - 07b_an_multivariable_cox_models_FULL_covidadmission_2ndVaccCensor
      - 07b_an_multivariable_cox_models_FULL_covid_death_2ndVaccCensor
    run: stata-mp:latest analysis/15_anHRfigure_all_outcomes_2021_SENSE.do
    outputs:
      moderately_sensitive:
        log: logs/15_an_tablecontents_HRtable_all_outcomes_ANALYSES_SENSE.log
        data: "output/15_an_tablecontents_HRtable_all_outcomes_ANALYSES_SENSE.txt"

  run_all:
    needs:
      - 02_an_data_checks
      - 03a_an_descriptive_tables
      - 03b_an_descriptive_table_1
      - 04a_an_descriptive_tables
      - 04b_an_descriptive_table_2
      - 06_univariate_analysis
      - 07a_an_multivariable_cox_models_demogADJ
      - 08_an_tablecontent_HRtable_covidadmission
      - 08_an_tablecontent_HRtable_covid_death
      - 08_an_tablecontent_HRtable_covid_tpp_prob
      - 11_an_interaction_HR_tables_forest_vaccine_strat_analysis_covid_tpp_prob
      - 11_an_interaction_HR_tables_forest_vaccine_main_analysis_covid_tpp_prob
      - 11_an_interaction_HR_tables_forest_covid_tpp_prob
      - 11_an_interaction_HR_tables_forest_covidadmission
      - 11_an_interaction_HR_tables_forest_covid_death
      - 15_anHRfigure_all_outcomes_2021
      - 15_anHRfigure_data_all_outcomes_2021_SENSE
    # In order to be valid this action needs to define a run commmand and
    # some output. We don't really care what these are but the below seems to
    # do the trick.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml
